Repository Alfresco/surf-webscripts, pull requests merged in 2020-10, with the labels that each got.

#87 Bugfix/apps 417 csrf token session fix
  spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/CSRFFilter.java
Labels: PR: partially-approved

#90 APPS-536 : Unable to login and use share via kerberos
  spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/CSRFFilter.java
Labels: PR: reviewed-approved

#91 Spring 5.2.9 update
  pom.xml
Labels: PR: unreviewed

#92 MNT-20195: Avoid displaying sensitive error messages
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/errorcode.lib.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/fbml.status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/json.status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/xml.status.ftl
Labels: PR: partially-approved

#94 APPS-595 : Changes from MNT-20195 break Travis build for alfresco-community-repo
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/fbml.status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/json.status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/status.ftl
  spring-webscripts/spring-webscripts/src/main/resources/webscripts/xml.status.ftl
Labels: PR: partially-approved
